# Generated by Django 4.2.6 on 2023-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('credit_hrs', models.CharField(max_length=10)),
                ('dept_id', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.CharField(max_length=20)),
                ('degree_name', models.CharField(max_length=100)),
                ('degree_level_name', models.CharField(max_length=20)),
                ('dept_id', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=50)),
                ('total_credit_hrs', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level_name', models.CharField(max_length=20)),
                ('degree_duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=50)),
                ('degree_id', models.CharField(max_length=20)),
                ('degree_name', models.CharField(max_length=100)),
                ('degree_level_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisite_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=25)),
                ('student_name', models.CharField(max_length=50)),
                ('student_type', models.CharField(max_length=50)),
                ('degree_id', models.CharField(max_length=20)),
                ('degree_name', models.CharField(max_length=100)),
                ('dept_id', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=50)),
                ('degree_level_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('credit_hrs', models.CharField(max_length=10)),
            ],
        ),
    ]
