# Generated by Django 4.2.6 on 2023-10-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degreechecklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_credit',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='transfer_credit',
            name='course_name',
        ),
    ]
