# Generated by Django 4.2.6 on 2023-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degreechecklist', '0003_delete_prerequisite_course_remove_degree_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree_level',
            name='degree_level_name',
            field=models.CharField(max_length=50),
        ),
    ]
